`timescale 1ns / 1ns

//
// Generative fractal-art generator, 1920x1080@60.
//
// A Julia set (z <- z^2 + c, z0 = pixel) whose parameter c does a bounded
// pseudo-random walk, so the structure keeps changing and never repeats,
// coloured by a cyclic jewel-tone palette that slowly rotates.
//
//   * c = 0.7885 * (cos t, sin t):  the angle t sweeps at an LFSR-driven speed
//     that never drops to zero (so the morph never freezes) and reverses only
//     occasionally, keeping c wandering the intricate Mandelbrot-boundary circle;
//   * the palette index adds a per-frame colour offset, so hues flow.
//
// Reuses the timing-closed streaming pipeline from the Mandelbrot/Julia
// projects. LUTs (unit circle, palette) are generated by tools/art_model.py.
//
module random_fractal_gen #(

	parameter video_hlength		= 2200,
	parameter video_vlength		= 1125,
	parameter video_hsync_pol	= 1,
	parameter video_hsync_len	= 44,
	parameter video_hbp_len		= 148,

	parameter video_h_visible	= 1920,
	parameter video_vsync_pol	= 1,
	parameter video_vsync_len	= 5,
	parameter video_vbp_len		= 36,
	parameter video_v_visible	= 1080,

	parameter N					= 12,	// iterations (== unrolled pipeline stages)
	parameter FRAC				= 14,	// Q4.14 fixed point
	parameter STRIDE			= 4,	// palette entries per escape band
	parameter COLOR_DIV			= 3		// colour offset advances every COLOR_DIV frames
)
(
	input				pixel_clock,
	input				reset,

	output				video_vsync,
	output				video_hsync,
	output				video_den,
	output				video_line_start,
	output	[23 : 0]	video_pixel_even,
	output	[23 : 0]	video_pixel_odd
);

	localparam T_HVIS_BEGIN	= video_hsync_len + video_hbp_len;
	localparam T_HVIS_END	= T_HVIS_BEGIN + video_h_visible - 1;
	localparam T_VVIS_BEGIN	= video_vsync_len + video_vbp_len;

	localparam signed [17 : 0]	ZR_STEP	= 18'sd27;
	localparam signed [17 : 0]	ZI_STEP	= 18'sd27;
	localparam signed [17 : 0]	ZR_MIN	= -(ZR_STEP * video_h_visible) / 2;
	localparam signed [17 : 0]	ZI_MIN	= -(ZI_STEP * video_v_visible) / 2;


	// c = 0.7885*(cos,sin) around a 256-step circle, Q4.14 (generated)
	function [35 : 0] c_lut(input [7 : 0] a);  // {c_re[17:0], c_im[17:0]}
		case(a)
			8'd0: c_lut = {18'h03277, 18'h00000};
			8'd1: c_lut = {18'h03273, 18'h0013D};
			8'd2: c_lut = {18'h03267, 18'h0027A};
			8'd3: c_lut = {18'h03254, 18'h003B6};
			8'd4: c_lut = {18'h03239, 18'h004F2};
			8'd5: c_lut = {18'h03216, 18'h0062D};
			8'd6: c_lut = {18'h031EB, 18'h00768};
			8'd7: c_lut = {18'h031B9, 18'h008A1};
			8'd8: c_lut = {18'h0317F, 18'h009D8};
			8'd9: c_lut = {18'h0313D, 18'h00B0F};
			8'd10: c_lut = {18'h030F4, 18'h00C43};
			8'd11: c_lut = {18'h030A3, 18'h00D76};
			8'd12: c_lut = {18'h0304B, 18'h00EA6};
			8'd13: c_lut = {18'h02FEB, 18'h00FD4};
			8'd14: c_lut = {18'h02F84, 18'h01100};
			8'd15: c_lut = {18'h02F15, 18'h01229};
			8'd16: c_lut = {18'h02E9F, 18'h01350};
			8'd17: c_lut = {18'h02E22, 18'h01473};
			8'd18: c_lut = {18'h02D9E, 18'h01593};
			8'd19: c_lut = {18'h02D13, 18'h016B0};
			8'd20: c_lut = {18'h02C81, 18'h017CA};
			8'd21: c_lut = {18'h02BE8, 18'h018E0};
			8'd22: c_lut = {18'h02B49, 18'h019F2};
			8'd23: c_lut = {18'h02AA2, 18'h01B00};
			8'd24: c_lut = {18'h029F6, 18'h01C09};
			8'd25: c_lut = {18'h02942, 18'h01D0F};
			8'd26: c_lut = {18'h02888, 18'h01E10};
			8'd27: c_lut = {18'h027C8, 18'h01F0C};
			8'd28: c_lut = {18'h02702, 18'h02004};
			8'd29: c_lut = {18'h02636, 18'h020F6};
			8'd30: c_lut = {18'h02564, 18'h021E4};
			8'd31: c_lut = {18'h0248C, 18'h022CC};
			8'd32: c_lut = {18'h023AF, 18'h023AF};
			8'd33: c_lut = {18'h022CC, 18'h0248C};
			8'd34: c_lut = {18'h021E4, 18'h02564};
			8'd35: c_lut = {18'h020F6, 18'h02636};
			8'd36: c_lut = {18'h02004, 18'h02702};
			8'd37: c_lut = {18'h01F0C, 18'h027C8};
			8'd38: c_lut = {18'h01E10, 18'h02888};
			8'd39: c_lut = {18'h01D0F, 18'h02942};
			8'd40: c_lut = {18'h01C09, 18'h029F6};
			8'd41: c_lut = {18'h01B00, 18'h02AA2};
			8'd42: c_lut = {18'h019F2, 18'h02B49};
			8'd43: c_lut = {18'h018E0, 18'h02BE8};
			8'd44: c_lut = {18'h017CA, 18'h02C81};
			8'd45: c_lut = {18'h016B0, 18'h02D13};
			8'd46: c_lut = {18'h01593, 18'h02D9E};
			8'd47: c_lut = {18'h01473, 18'h02E22};
			8'd48: c_lut = {18'h01350, 18'h02E9F};
			8'd49: c_lut = {18'h01229, 18'h02F15};
			8'd50: c_lut = {18'h01100, 18'h02F84};
			8'd51: c_lut = {18'h00FD4, 18'h02FEB};
			8'd52: c_lut = {18'h00EA6, 18'h0304B};
			8'd53: c_lut = {18'h00D76, 18'h030A3};
			8'd54: c_lut = {18'h00C43, 18'h030F4};
			8'd55: c_lut = {18'h00B0F, 18'h0313D};
			8'd56: c_lut = {18'h009D8, 18'h0317F};
			8'd57: c_lut = {18'h008A1, 18'h031B9};
			8'd58: c_lut = {18'h00768, 18'h031EB};
			8'd59: c_lut = {18'h0062D, 18'h03216};
			8'd60: c_lut = {18'h004F2, 18'h03239};
			8'd61: c_lut = {18'h003B6, 18'h03254};
			8'd62: c_lut = {18'h0027A, 18'h03267};
			8'd63: c_lut = {18'h0013D, 18'h03273};
			8'd64: c_lut = {18'h00000, 18'h03277};
			8'd65: c_lut = {18'h3FEC3, 18'h03273};
			8'd66: c_lut = {18'h3FD86, 18'h03267};
			8'd67: c_lut = {18'h3FC4A, 18'h03254};
			8'd68: c_lut = {18'h3FB0E, 18'h03239};
			8'd69: c_lut = {18'h3F9D3, 18'h03216};
			8'd70: c_lut = {18'h3F898, 18'h031EB};
			8'd71: c_lut = {18'h3F75F, 18'h031B9};
			8'd72: c_lut = {18'h3F628, 18'h0317F};
			8'd73: c_lut = {18'h3F4F1, 18'h0313D};
			8'd74: c_lut = {18'h3F3BD, 18'h030F4};
			8'd75: c_lut = {18'h3F28A, 18'h030A3};
			8'd76: c_lut = {18'h3F15A, 18'h0304B};
			8'd77: c_lut = {18'h3F02C, 18'h02FEB};
			8'd78: c_lut = {18'h3EF00, 18'h02F84};
			8'd79: c_lut = {18'h3EDD7, 18'h02F15};
			8'd80: c_lut = {18'h3ECB0, 18'h02E9F};
			8'd81: c_lut = {18'h3EB8D, 18'h02E22};
			8'd82: c_lut = {18'h3EA6D, 18'h02D9E};
			8'd83: c_lut = {18'h3E950, 18'h02D13};
			8'd84: c_lut = {18'h3E836, 18'h02C81};
			8'd85: c_lut = {18'h3E720, 18'h02BE8};
			8'd86: c_lut = {18'h3E60E, 18'h02B49};
			8'd87: c_lut = {18'h3E500, 18'h02AA2};
			8'd88: c_lut = {18'h3E3F7, 18'h029F6};
			8'd89: c_lut = {18'h3E2F1, 18'h02942};
			8'd90: c_lut = {18'h3E1F0, 18'h02888};
			8'd91: c_lut = {18'h3E0F4, 18'h027C8};
			8'd92: c_lut = {18'h3DFFC, 18'h02702};
			8'd93: c_lut = {18'h3DF0A, 18'h02636};
			8'd94: c_lut = {18'h3DE1C, 18'h02564};
			8'd95: c_lut = {18'h3DD34, 18'h0248C};
			8'd96: c_lut = {18'h3DC51, 18'h023AF};
			8'd97: c_lut = {18'h3DB74, 18'h022CC};
			8'd98: c_lut = {18'h3DA9C, 18'h021E4};
			8'd99: c_lut = {18'h3D9CA, 18'h020F6};
			8'd100: c_lut = {18'h3D8FE, 18'h02004};
			8'd101: c_lut = {18'h3D838, 18'h01F0C};
			8'd102: c_lut = {18'h3D778, 18'h01E10};
			8'd103: c_lut = {18'h3D6BE, 18'h01D0F};
			8'd104: c_lut = {18'h3D60A, 18'h01C09};
			8'd105: c_lut = {18'h3D55E, 18'h01B00};
			8'd106: c_lut = {18'h3D4B7, 18'h019F2};
			8'd107: c_lut = {18'h3D418, 18'h018E0};
			8'd108: c_lut = {18'h3D37F, 18'h017CA};
			8'd109: c_lut = {18'h3D2ED, 18'h016B0};
			8'd110: c_lut = {18'h3D262, 18'h01593};
			8'd111: c_lut = {18'h3D1DE, 18'h01473};
			8'd112: c_lut = {18'h3D161, 18'h01350};
			8'd113: c_lut = {18'h3D0EB, 18'h01229};
			8'd114: c_lut = {18'h3D07C, 18'h01100};
			8'd115: c_lut = {18'h3D015, 18'h00FD4};
			8'd116: c_lut = {18'h3CFB5, 18'h00EA6};
			8'd117: c_lut = {18'h3CF5D, 18'h00D76};
			8'd118: c_lut = {18'h3CF0C, 18'h00C43};
			8'd119: c_lut = {18'h3CEC3, 18'h00B0F};
			8'd120: c_lut = {18'h3CE81, 18'h009D8};
			8'd121: c_lut = {18'h3CE47, 18'h008A1};
			8'd122: c_lut = {18'h3CE15, 18'h00768};
			8'd123: c_lut = {18'h3CDEA, 18'h0062D};
			8'd124: c_lut = {18'h3CDC7, 18'h004F2};
			8'd125: c_lut = {18'h3CDAC, 18'h003B6};
			8'd126: c_lut = {18'h3CD99, 18'h0027A};
			8'd127: c_lut = {18'h3CD8D, 18'h0013D};
			8'd128: c_lut = {18'h3CD89, 18'h00000};
			8'd129: c_lut = {18'h3CD8D, 18'h3FEC3};
			8'd130: c_lut = {18'h3CD99, 18'h3FD86};
			8'd131: c_lut = {18'h3CDAC, 18'h3FC4A};
			8'd132: c_lut = {18'h3CDC7, 18'h3FB0E};
			8'd133: c_lut = {18'h3CDEA, 18'h3F9D3};
			8'd134: c_lut = {18'h3CE15, 18'h3F898};
			8'd135: c_lut = {18'h3CE47, 18'h3F75F};
			8'd136: c_lut = {18'h3CE81, 18'h3F628};
			8'd137: c_lut = {18'h3CEC3, 18'h3F4F1};
			8'd138: c_lut = {18'h3CF0C, 18'h3F3BD};
			8'd139: c_lut = {18'h3CF5D, 18'h3F28A};
			8'd140: c_lut = {18'h3CFB5, 18'h3F15A};
			8'd141: c_lut = {18'h3D015, 18'h3F02C};
			8'd142: c_lut = {18'h3D07C, 18'h3EF00};
			8'd143: c_lut = {18'h3D0EB, 18'h3EDD7};
			8'd144: c_lut = {18'h3D161, 18'h3ECB0};
			8'd145: c_lut = {18'h3D1DE, 18'h3EB8D};
			8'd146: c_lut = {18'h3D262, 18'h3EA6D};
			8'd147: c_lut = {18'h3D2ED, 18'h3E950};
			8'd148: c_lut = {18'h3D37F, 18'h3E836};
			8'd149: c_lut = {18'h3D418, 18'h3E720};
			8'd150: c_lut = {18'h3D4B7, 18'h3E60E};
			8'd151: c_lut = {18'h3D55E, 18'h3E500};
			8'd152: c_lut = {18'h3D60A, 18'h3E3F7};
			8'd153: c_lut = {18'h3D6BE, 18'h3E2F1};
			8'd154: c_lut = {18'h3D778, 18'h3E1F0};
			8'd155: c_lut = {18'h3D838, 18'h3E0F4};
			8'd156: c_lut = {18'h3D8FE, 18'h3DFFC};
			8'd157: c_lut = {18'h3D9CA, 18'h3DF0A};
			8'd158: c_lut = {18'h3DA9C, 18'h3DE1C};
			8'd159: c_lut = {18'h3DB74, 18'h3DD34};
			8'd160: c_lut = {18'h3DC51, 18'h3DC51};
			8'd161: c_lut = {18'h3DD34, 18'h3DB74};
			8'd162: c_lut = {18'h3DE1C, 18'h3DA9C};
			8'd163: c_lut = {18'h3DF0A, 18'h3D9CA};
			8'd164: c_lut = {18'h3DFFC, 18'h3D8FE};
			8'd165: c_lut = {18'h3E0F4, 18'h3D838};
			8'd166: c_lut = {18'h3E1F0, 18'h3D778};
			8'd167: c_lut = {18'h3E2F1, 18'h3D6BE};
			8'd168: c_lut = {18'h3E3F7, 18'h3D60A};
			8'd169: c_lut = {18'h3E500, 18'h3D55E};
			8'd170: c_lut = {18'h3E60E, 18'h3D4B7};
			8'd171: c_lut = {18'h3E720, 18'h3D418};
			8'd172: c_lut = {18'h3E836, 18'h3D37F};
			8'd173: c_lut = {18'h3E950, 18'h3D2ED};
			8'd174: c_lut = {18'h3EA6D, 18'h3D262};
			8'd175: c_lut = {18'h3EB8D, 18'h3D1DE};
			8'd176: c_lut = {18'h3ECB0, 18'h3D161};
			8'd177: c_lut = {18'h3EDD7, 18'h3D0EB};
			8'd178: c_lut = {18'h3EF00, 18'h3D07C};
			8'd179: c_lut = {18'h3F02C, 18'h3D015};
			8'd180: c_lut = {18'h3F15A, 18'h3CFB5};
			8'd181: c_lut = {18'h3F28A, 18'h3CF5D};
			8'd182: c_lut = {18'h3F3BD, 18'h3CF0C};
			8'd183: c_lut = {18'h3F4F1, 18'h3CEC3};
			8'd184: c_lut = {18'h3F628, 18'h3CE81};
			8'd185: c_lut = {18'h3F75F, 18'h3CE47};
			8'd186: c_lut = {18'h3F898, 18'h3CE15};
			8'd187: c_lut = {18'h3F9D3, 18'h3CDEA};
			8'd188: c_lut = {18'h3FB0E, 18'h3CDC7};
			8'd189: c_lut = {18'h3FC4A, 18'h3CDAC};
			8'd190: c_lut = {18'h3FD86, 18'h3CD99};
			8'd191: c_lut = {18'h3FEC3, 18'h3CD8D};
			8'd192: c_lut = {18'h00000, 18'h3CD89};
			8'd193: c_lut = {18'h0013D, 18'h3CD8D};
			8'd194: c_lut = {18'h0027A, 18'h3CD99};
			8'd195: c_lut = {18'h003B6, 18'h3CDAC};
			8'd196: c_lut = {18'h004F2, 18'h3CDC7};
			8'd197: c_lut = {18'h0062D, 18'h3CDEA};
			8'd198: c_lut = {18'h00768, 18'h3CE15};
			8'd199: c_lut = {18'h008A1, 18'h3CE47};
			8'd200: c_lut = {18'h009D8, 18'h3CE81};
			8'd201: c_lut = {18'h00B0F, 18'h3CEC3};
			8'd202: c_lut = {18'h00C43, 18'h3CF0C};
			8'd203: c_lut = {18'h00D76, 18'h3CF5D};
			8'd204: c_lut = {18'h00EA6, 18'h3CFB5};
			8'd205: c_lut = {18'h00FD4, 18'h3D015};
			8'd206: c_lut = {18'h01100, 18'h3D07C};
			8'd207: c_lut = {18'h01229, 18'h3D0EB};
			8'd208: c_lut = {18'h01350, 18'h3D161};
			8'd209: c_lut = {18'h01473, 18'h3D1DE};
			8'd210: c_lut = {18'h01593, 18'h3D262};
			8'd211: c_lut = {18'h016B0, 18'h3D2ED};
			8'd212: c_lut = {18'h017CA, 18'h3D37F};
			8'd213: c_lut = {18'h018E0, 18'h3D418};
			8'd214: c_lut = {18'h019F2, 18'h3D4B7};
			8'd215: c_lut = {18'h01B00, 18'h3D55E};
			8'd216: c_lut = {18'h01C09, 18'h3D60A};
			8'd217: c_lut = {18'h01D0F, 18'h3D6BE};
			8'd218: c_lut = {18'h01E10, 18'h3D778};
			8'd219: c_lut = {18'h01F0C, 18'h3D838};
			8'd220: c_lut = {18'h02004, 18'h3D8FE};
			8'd221: c_lut = {18'h020F6, 18'h3D9CA};
			8'd222: c_lut = {18'h021E4, 18'h3DA9C};
			8'd223: c_lut = {18'h022CC, 18'h3DB74};
			8'd224: c_lut = {18'h023AF, 18'h3DC51};
			8'd225: c_lut = {18'h0248C, 18'h3DD34};
			8'd226: c_lut = {18'h02564, 18'h3DE1C};
			8'd227: c_lut = {18'h02636, 18'h3DF0A};
			8'd228: c_lut = {18'h02702, 18'h3DFFC};
			8'd229: c_lut = {18'h027C8, 18'h3E0F4};
			8'd230: c_lut = {18'h02888, 18'h3E1F0};
			8'd231: c_lut = {18'h02942, 18'h3E2F1};
			8'd232: c_lut = {18'h029F6, 18'h3E3F7};
			8'd233: c_lut = {18'h02AA2, 18'h3E500};
			8'd234: c_lut = {18'h02B49, 18'h3E60E};
			8'd235: c_lut = {18'h02BE8, 18'h3E720};
			8'd236: c_lut = {18'h02C81, 18'h3E836};
			8'd237: c_lut = {18'h02D13, 18'h3E950};
			8'd238: c_lut = {18'h02D9E, 18'h3EA6D};
			8'd239: c_lut = {18'h02E22, 18'h3EB8D};
			8'd240: c_lut = {18'h02E9F, 18'h3ECB0};
			8'd241: c_lut = {18'h02F15, 18'h3EDD7};
			8'd242: c_lut = {18'h02F84, 18'h3EF00};
			8'd243: c_lut = {18'h02FEB, 18'h3F02C};
			8'd244: c_lut = {18'h0304B, 18'h3F15A};
			8'd245: c_lut = {18'h030A3, 18'h3F28A};
			8'd246: c_lut = {18'h030F4, 18'h3F3BD};
			8'd247: c_lut = {18'h0313D, 18'h3F4F1};
			8'd248: c_lut = {18'h0317F, 18'h3F628};
			8'd249: c_lut = {18'h031B9, 18'h3F75F};
			8'd250: c_lut = {18'h031EB, 18'h3F898};
			8'd251: c_lut = {18'h03216, 18'h3F9D3};
			8'd252: c_lut = {18'h03239, 18'h3FB0E};
			8'd253: c_lut = {18'h03254, 18'h3FC4A};
			8'd254: c_lut = {18'h03267, 18'h3FD86};
			8'd255: c_lut = {18'h03273, 18'h3FEC3};
			default: c_lut = 36'h0;
		endcase
	endfunction

	// cyclic jewel-tone palette x64 (generated)
	function [23 : 0] pal(input [5 : 0] idx);
		case(idx)
			6'd0: pal = 24'h0A143C;
			6'd1: pal = 24'h0C1D4E;
			6'd2: pal = 24'h0F265F;
			6'd3: pal = 24'h122E70;
			6'd4: pal = 24'h143782;
			6'd5: pal = 24'h164094;
			6'd6: pal = 24'h1948A5;
			6'd7: pal = 24'h1C51B6;
			6'd8: pal = 24'h1E5AC8;
			6'd9: pal = 24'h1F68CA;
			6'd10: pal = 24'h2076CD;
			6'd11: pal = 24'h2283D0;
			6'd12: pal = 24'h2391D2;
			6'd13: pal = 24'h249FD4;
			6'd14: pal = 24'h26ACD7;
			6'd15: pal = 24'h27BADA;
			6'd16: pal = 24'h28C8DC;
			6'd17: pal = 24'h32CDD7;
			6'd18: pal = 24'h3CD2D2;
			6'd19: pal = 24'h46D7CD;
			6'd20: pal = 24'h50DCC8;
			6'd21: pal = 24'h5AE1C3;
			6'd22: pal = 24'h64E6BE;
			6'd23: pal = 24'h6EEBB9;
			6'd24: pal = 24'h78F0B4;
			6'd25: pal = 24'h88EFAC;
			6'd26: pal = 24'h98EEA5;
			6'd27: pal = 24'hA9EC9E;
			6'd28: pal = 24'hB9EB96;
			6'd29: pal = 24'hC9EA8E;
			6'd30: pal = 24'hDAE887;
			6'd31: pal = 24'hEAE780;
			6'd32: pal = 24'hFAE678;
			6'd33: pal = 24'hFADB74;
			6'd34: pal = 24'hFAD070;
			6'd35: pal = 24'hFAC46D;
			6'd36: pal = 24'hFAB969;
			6'd37: pal = 24'hFAAE65;
			6'd38: pal = 24'hFAA262;
			6'd39: pal = 24'hFA975E;
			6'd40: pal = 24'hFA8C5A;
			6'd41: pal = 24'hF88463;
			6'd42: pal = 24'hF57D6C;
			6'd43: pal = 24'hF27674;
			6'd44: pal = 24'hF06E7D;
			6'd45: pal = 24'hEE6686;
			6'd46: pal = 24'hEB5F8E;
			6'd47: pal = 24'hE85897;
			6'd48: pal = 24'hE650A0;
			6'd49: pal = 24'hD84EA2;
			6'd50: pal = 24'hCA4BA5;
			6'd51: pal = 24'hBD48A8;
			6'd52: pal = 24'hAF46AA;
			6'd53: pal = 24'hA144AC;
			6'd54: pal = 24'h9441AF;
			6'd55: pal = 24'h863EB2;
			6'd56: pal = 24'h783CB4;
			6'd57: pal = 24'h6A37A5;
			6'd58: pal = 24'h5C3296;
			6'd59: pal = 24'h4F2D87;
			6'd60: pal = 24'h412878;
			6'd61: pal = 24'h332369;
			6'd62: pal = 24'h261E5A;
			6'd63: pal = 24'h18194B;
			default: pal = 24'h000000;
		endcase
	endfunction

	// ------------------------------------------------------------------
	// video timing
	// ------------------------------------------------------------------

	wire	[13 : 0]	timing_h_pos;
	wire	[13 : 0]	timing_v_pos;
	wire	[13 : 0]	pixel_x_nc;
	wire	[13 : 0]	pixel_y_nc;

	wire				vsync_int;
	wire				hsync_int;
	wire				den_int;
	wire				line_start_int;

	video_timing_ctrl #(
		.video_hlength(video_hlength),
		.video_vlength(video_vlength),
		.video_hsync_pol(video_hsync_pol),
		.video_hsync_len(video_hsync_len),
		.video_hbp_len(video_hbp_len),
		.video_h_visible(video_h_visible),
		.video_vsync_pol(video_vsync_pol),
		.video_vsync_len(video_vsync_len),
		.video_vbp_len(video_vbp_len),
		.video_v_visible(video_v_visible)
	)video_timing_ctrl_inst0(
		.pixel_clock		(pixel_clock),
		.reset				(reset),
		.ext_sync			(1'b0),
		.timing_h_pos		(timing_h_pos),
		.timing_v_pos		(timing_v_pos),
		.pixel_x			(pixel_x_nc),
		.pixel_y			(pixel_y_nc),
		.video_vsync		(vsync_int),
		.video_hsync		(hsync_int),
		.video_den			(den_int),
		.video_line_start	(line_start_int)
	);

	wire frame_tick = (timing_h_pos == 0) && (timing_v_pos == 0);

	// ------------------------------------------------------------------
	// pseudo-random walk of c = R*(cos t, sin t)
	// ------------------------------------------------------------------

	reg		[15 : 0]	lfsr		= 16'hBEEF;
	always@(posedge pixel_clock)begin
		if(reset)			lfsr <= 16'hBEEF;
		else if(frame_tick)	lfsr <= {lfsr[14:0], lfsr[15]^lfsr[13]^lfsr[12]^lfsr[10]};
	end

	// angle: advances EVERY frame at a speed that never reaches zero, so the
	// morph never freezes. The speed MAGNITUDE random-walks in [SPD_MIN..SPD_MAX]
	// (LFSR nudge every 8 frames) and a separate direction bit reverses only
	// occasionally (~1/32 of turns) -> continuous, wandering, non-repeating motion.
	localparam [2 : 0]	SPD_MIN = 3'd3, SPD_MAX = 3'd7;
	reg		[11 : 0]	theta		= 0;
	reg		[2 : 0]		theta_spd	= 3'd4;		// |angular velocity|, never 0
	reg					theta_dir	= 1'b0;		// 0 = forward, 1 = reverse
	reg		[2 : 0]		nudge_div	= 0;

	wire	[11 : 0]	spd_ext = {9'd0, theta_spd};
	wire	[11 : 0]	tv_ext  = theta_dir ? (~spd_ext + 12'd1) : spd_ext;

	always@(posedge pixel_clock)begin
		if(reset)begin
			theta <= 0; theta_spd <= 3'd4; theta_dir <= 1'b0; nudge_div <= 0;
		end else if(frame_tick)begin
			theta <= theta + tv_ext;
			if(nudge_div == 3'd7)begin
				nudge_div <= 0;
				// random-walk the speed within its band (clamped, never 0)
				if(lfsr[1] & (theta_spd < SPD_MAX))			theta_spd <= theta_spd + 3'd1;
				else if(~lfsr[1] & (theta_spd > SPD_MIN))	theta_spd <= theta_spd - 3'd1;
				// reverse direction only rarely -> long, sweeping arcs
				if(lfsr[7] & lfsr[5] & lfsr[4] & lfsr[2] & lfsr[0])	theta_dir <= ~theta_dir;
			end else
				nudge_div <= nudge_div + 1'b1;
		end
	end

	// c from the fixed-radius circle LUT, indexed by the random-walk angle.
	// R is baked into the LUT (no runtime multiply) -> this sidesteps a Verilog
	// width pitfall and leaves every DSP for the iteration; registering the LUT
	// output keeps its 256:1 mux off the DSP critical path.
	reg		[35 : 0]	c_word;
	always@(posedge pixel_clock)
		c_word <= c_lut(theta[11 : 4]);
	wire signed	[17 : 0]	c_re = c_word[35 : 18];
	wire signed	[17 : 0]	c_im = c_word[17 : 0];

	// ------------------------------------------------------------------
	// colour cycling: palette offset advances every COLOR_DIV frames
	// ------------------------------------------------------------------

	reg		[7 : 0]		color_div	= 0;
	reg		[5 : 0]		color_offset= 0;
	always@(posedge pixel_clock)begin
		if(reset)begin
			color_div <= 0; color_offset <= 0;
		end else if(frame_tick)begin
			if(color_div == (COLOR_DIV - 1))begin
				color_div <= 0;
				color_offset <= color_offset + 1'b1;
			end else
				color_div <= color_div + 1'b1;
		end
	end

	// ------------------------------------------------------------------
	// pixel -> z0 coordinate (DDA), aligned with den_int
	// ------------------------------------------------------------------

	wire pix_load  = (timing_h_pos == (T_HVIS_BEGIN - 1));
	wire line_step = (timing_h_pos == (T_HVIS_END + 1));
	wire frame_load= (timing_v_pos == (T_VVIS_BEGIN - 1));

	reg signed	[17 : 0]	zi_line	= 0;
	always@(posedge pixel_clock)begin
		if(line_step)
			zi_line <= frame_load ? ZI_MIN : (zi_line + ZI_STEP);
	end

	reg signed	[17 : 0]	zr_pixel = 0;
	always@(posedge pixel_clock)begin
		if(pix_load)	zr_pixel <= ZR_MIN;
		else			zr_pixel <= zr_pixel + ZR_STEP;
	end

	// ------------------------------------------------------------------
	// unrolled iteration pipeline (identical engine)
	// ------------------------------------------------------------------

	reg signed	[17 : 0]	zr_p [0 : N];
	reg signed	[17 : 0]	zi_p [0 : N];
	reg signed	[17 : 0]	cr_p [0 : N];
	reg signed	[17 : 0]	ci_p [0 : N];
	reg			[6 : 0]		cnt_p [0 : N];
	reg						esc_p [0 : N];

	always@(posedge pixel_clock)begin
		zr_p[0] <= zr_pixel;
		zi_p[0] <= zi_line;
		cr_p[0] <= c_re;
		ci_p[0] <= c_im;
		cnt_p[0] <= 7'd0;
		esc_p[0] <= 1'b0;
	end

	genvar i;
	generate for(i = 0; i < N; i = i + 1) begin : iter

		reg signed	[35 : 0]	m_rr, m_ii, m_ri;
		reg signed	[17 : 0]	s1_zr, s1_zi, s1_cr, s1_ci;
		reg			[6 : 0]		s1_cnt;
		reg						s1_esc;

		always@(posedge pixel_clock)begin
			m_rr  <= zr_p[i] * zr_p[i];
			m_ii  <= zi_p[i] * zi_p[i];
			m_ri  <= zr_p[i] * zi_p[i];
			s1_zr <= zr_p[i];	s1_zi <= zi_p[i];
			s1_cr <= cr_p[i];	s1_ci <= ci_p[i];
			s1_cnt<= cnt_p[i];	s1_esc <= esc_p[i];
		end

		reg signed	[35 : 0]	s2_diff, s2_mag, s2_ri;
		reg signed	[17 : 0]	s2_zr, s2_zi, s2_cr, s2_ci;
		reg			[6 : 0]		s2_cnt;
		reg						s2_esc;

		always@(posedge pixel_clock)begin
			s2_diff <= m_rr - m_ii;
			s2_mag  <= m_rr + m_ii;
			s2_ri   <= m_ri;
			s2_zr <= s1_zr;		s2_zi <= s1_zi;
			s2_cr <= s1_cr;		s2_ci <= s1_ci;
			s2_cnt<= s1_cnt;	s2_esc <= s1_esc;
		end

		wire escaped_now = s2_esc | (|s2_mag[35 : 30]);

		always@(posedge pixel_clock)begin
			cr_p[i+1] <= s2_cr;
			ci_p[i+1] <= s2_ci;
			esc_p[i+1] <= escaped_now;
			if(escaped_now)begin
				cnt_p[i+1] <= s2_cnt;
				zr_p[i+1]  <= s2_zr;
				zi_p[i+1]  <= s2_zi;
			end else begin
				cnt_p[i+1] <= s2_cnt + 1'b1;
				zr_p[i+1]  <= (s2_diff >>> FRAC) + s2_cr;
				zi_p[i+1]  <= (s2_ri >>> (FRAC - 1)) + s2_ci;
			end
		end
	end endgenerate

	// ------------------------------------------------------------------
	// colour: cyclic palette with per-frame offset (2 registered stages)
	// ------------------------------------------------------------------

	localparam PIPE = 3*N + 4;

	// Interior (in-set) pixels are shaded by |z_final| = |zr|+|zi| instead of
	// black, so the middle reads as a glowing fill (final z is already carried
	// down the pipeline). Split into two stages for timing headroom.
	wire signed	[17 : 0]	fzr = zr_p[N];
	wire signed	[17 : 0]	fzi = zi_p[N];
	wire		[17 : 0]	azr = fzr[17] ? (~fzr + 18'd1) : fzr;
	wire		[17 : 0]	azi = fzi[17] ? (~fzi + 18'd1) : fzi;

	reg		[18 : 0]	man_reg;	// |zr| + |zi|
	reg		[6 : 0]		cnt_reg;
	always@(posedge pixel_clock)begin
		man_reg <= azr + azi;
		cnt_reg <= cnt_p[N];
	end

	reg		[5 : 0]		pal_idx;
	always@(posedge pixel_clock)begin
		if(cnt_reg == N)	pal_idx <= (man_reg >> 9) + color_offset + 6'd8;	// interior glow
		else				pal_idx <= (cnt_reg << 2) + color_offset;			// escape bands
	end

	reg		[23 : 0]	color;
	always@(posedge pixel_clock)
		color <= pal(pal_idx);

	reg		[PIPE-1 : 0]	den_dly, hsync_dly, vsync_dly, line_start_dly;
	always@(posedge pixel_clock)begin
		den_dly			<= {den_dly[PIPE-2 : 0], den_int};
		hsync_dly		<= {hsync_dly[PIPE-2 : 0], hsync_int};
		vsync_dly		<= {vsync_dly[PIPE-2 : 0], vsync_int};
		line_start_dly	<= {line_start_dly[PIPE-2 : 0], line_start_int};
	end

	wire den_out = den_dly[PIPE-1];

	assign video_den		= den_out;
	assign video_hsync		= hsync_dly[PIPE-1];
	assign video_vsync		= vsync_dly[PIPE-1];
	assign video_line_start	= line_start_dly[PIPE-1];

	assign video_pixel_even	= den_out ? color : 24'h000000;
	assign video_pixel_odd	= den_out ? color : 24'h000000;

endmodule
