`timescale 1ns / 1ns

//
// Real-time Mandelbrot-set generator, 1920x1080@60.
//
// The escape-time iteration  z <- z^2 + c  (z0 = 0) is evaluated per pixel
// with a fully-unrolled, streaming pipeline: one pixel enters and one exits
// every clock, so it feeds the 150 MHz video stream directly (no framebuffer).
// N iterations are unrolled; each iteration is 2 pipeline stages
//   stage A : the three products  zr*zr, zi*zi, zr*zi   (-> DSP)
//   stage B : z update, escape test, iteration count
// Fixed point is Q4.14 (signed 18-bit) so each product is one 18x18 DSP.
// Pixel -> complex plane is a DDA (adders): cr steps per pixel, ci per line.
// The iteration count (0..N) is mapped to colour by a palette LUT.
// den/hsync/vsync are delayed by the pipeline depth (2N+2) to match.
//
module mandelbrot_gen #(

	parameter video_hlength		= 2200,
	parameter video_vlength		= 1125,
	parameter video_hsync_pol	= 1,
	parameter video_hsync_len	= 44,
	parameter video_hbp_len		= 148,

	parameter video_h_visible	= 1920,
	parameter video_vsync_pol	= 1,
	parameter video_vsync_len	= 5,
	parameter video_vbp_len		= 36,
	parameter video_v_visible	= 1080,

	parameter N					= 14,	// iterations (== unrolled pipeline stages)
	parameter FRAC				= 14	// Q4.14 fixed point
)
(
	input				pixel_clock,
	input				reset,

	output				video_vsync,
	output				video_hsync,
	output				video_den,
	output				video_line_start,
	output	[23 : 0]	video_pixel_even,
	output	[23 : 0]	video_pixel_odd
);

	// active-region boundaries in raster counter space
	localparam T_HVIS_BEGIN	= video_hsync_len + video_hbp_len;			// 192
	localparam T_HVIS_END	= T_HVIS_BEGIN + video_h_visible - 1;		// 2111
	localparam T_VVIS_BEGIN	= video_vsync_len + video_vbp_len;			// 41

	// view window: cr in [-2.5, +1.0], square pixels (same step for ci)
	localparam signed [17 : 0]	CR_STEP	= 18'sd30;		// ~0.00183 / pixel in Q4.14
	localparam signed [17 : 0]	CI_STEP	= 18'sd30;
	localparam signed [17 : 0]	CR_MIN	= -18'sd40960;	// -2.5
	localparam signed [17 : 0]	CI_MIN	= -(CI_STEP * video_v_visible) / 2;	// centred
	localparam signed [35 : 0]	ESCAPE	= 36'sd1073741824;	// 4.0 in Q8.28

	// iteration count -> RGB ("teal & orange", generated by tools/mandelbrot_model.py)
	function [23 : 0] palette(input [6 : 0] cnt);
		case(cnt)
			7'd0: palette = 24'h061626;
			7'd1: palette = 24'h0B3548;
			7'd2: palette = 24'h105469;
			7'd3: palette = 24'h17788B;
			7'd4: palette = 24'h209DAC;
			7'd5: palette = 24'h36BBC5;
			7'd6: palette = 24'h52D5DB;
			7'd7: palette = 24'h76E8EA;
			7'd8: palette = 24'hA2F4F2;
			7'd9: palette = 24'hD0F9F2;
			7'd10: palette = 24'hF9F1E4;
			7'd11: palette = 24'hF4A97E;
			7'd12: palette = 24'hD76D28;
			7'd13: palette = 24'h78281C;
			7'd14: palette = 24'h000000;
			default: palette = 24'h000000;
		endcase
	endfunction

	// ------------------------------------------------------------------
	// video timing
	// ------------------------------------------------------------------

	wire	[13 : 0]	timing_h_pos;
	wire	[13 : 0]	timing_v_pos;
	wire	[13 : 0]	pixel_x_nc;
	wire	[13 : 0]	pixel_y_nc;

	wire				vsync_int;
	wire				hsync_int;
	wire				den_int;
	wire				line_start_int;

	video_timing_ctrl #(
		.video_hlength(video_hlength),
		.video_vlength(video_vlength),
		.video_hsync_pol(video_hsync_pol),
		.video_hsync_len(video_hsync_len),
		.video_hbp_len(video_hbp_len),
		.video_h_visible(video_h_visible),
		.video_vsync_pol(video_vsync_pol),
		.video_vsync_len(video_vsync_len),
		.video_vbp_len(video_vbp_len),
		.video_v_visible(video_v_visible)
	)video_timing_ctrl_inst0(
		.pixel_clock		(pixel_clock),
		.reset				(reset),
		.ext_sync			(1'b0),
		.timing_h_pos		(timing_h_pos),
		.timing_v_pos		(timing_v_pos),
		.pixel_x			(pixel_x_nc),
		.pixel_y			(pixel_y_nc),
		.video_vsync		(vsync_int),
		.video_hsync		(hsync_int),
		.video_den			(den_int),
		.video_line_start	(line_start_int)
	);

	// ------------------------------------------------------------------
	// pixel -> complex-plane coordinate (DDA, adders only)
	// cr_cur / ci_line are aligned with den_int (0 extra latency)
	// ------------------------------------------------------------------

	wire pix_load  = (timing_h_pos == (T_HVIS_BEGIN - 1));
	wire line_step = (timing_h_pos == (T_HVIS_END + 1));
	wire frame_load= (timing_v_pos == (T_VVIS_BEGIN - 1));

	reg signed	[17 : 0]	ci_line	= 0;
	always@(posedge pixel_clock)begin
		if(line_step)
			ci_line <= frame_load ? CI_MIN : (ci_line + CI_STEP);
	end

	reg signed	[17 : 0]	cr_cur	= 0;
	always@(posedge pixel_clock)begin
		if(pix_load)	cr_cur <= CR_MIN;
		else			cr_cur <= cr_cur + CR_STEP;
	end

	// ------------------------------------------------------------------
	// unrolled iteration pipeline
	// ------------------------------------------------------------------

	reg signed	[17 : 0]	zr_p [0 : N];
	reg signed	[17 : 0]	zi_p [0 : N];
	reg signed	[17 : 0]	cr_p [0 : N];
	reg signed	[17 : 0]	ci_p [0 : N];
	reg			[6 : 0]		cnt_p [0 : N];
	reg						esc_p [0 : N];

	// stage 0: inject c, z = 0
	always@(posedge pixel_clock)begin
		zr_p[0] <= 18'sd0;
		zi_p[0] <= 18'sd0;
		cr_p[0] <= cr_cur;
		ci_p[0] <= ci_line;
		cnt_p[0] <= 7'd0;
		esc_p[0] <= 1'b0;
	end

	// Each iteration is 3 registered stages so no two DSPs are chained
	// combinationally:
	//   stage 1 : the three products (registered DSP outputs)
	//   stage 2 : zr^2-zi^2, zr^2+zi^2 (registered adders)
	//   stage 3 : + c, escape test, count, freeze (registered)
	// The products feed both the difference and the sum, which stops the
	// tool from folding a product+add into one MULTADD and eating the
	// register between DSP stages.
	genvar i;
	generate for(i = 0; i < N; i = i + 1) begin : iter

		// ---- stage 1: products ----
		reg signed	[35 : 0]	m_rr, m_ii, m_ri;
		reg signed	[17 : 0]	s1_zr, s1_zi, s1_cr, s1_ci;
		reg			[6 : 0]		s1_cnt;
		reg						s1_esc;

		always@(posedge pixel_clock)begin
			m_rr  <= zr_p[i] * zr_p[i];
			m_ii  <= zi_p[i] * zi_p[i];
			m_ri  <= zr_p[i] * zi_p[i];
			s1_zr <= zr_p[i];	s1_zi <= zi_p[i];
			s1_cr <= cr_p[i];	s1_ci <= ci_p[i];
			s1_cnt<= cnt_p[i];	s1_esc <= esc_p[i];
		end

		// ---- stage 2: combine products ----
		reg signed	[35 : 0]	s2_diff, s2_mag, s2_ri;
		reg signed	[17 : 0]	s2_zr, s2_zi, s2_cr, s2_ci;
		reg			[6 : 0]		s2_cnt;
		reg						s2_esc;

		always@(posedge pixel_clock)begin
			s2_diff <= m_rr - m_ii;		// zr^2 - zi^2
			s2_mag  <= m_rr + m_ii;		// |z|^2
			s2_ri   <= m_ri;
			s2_zr <= s1_zr;		s2_zi <= s1_zi;
			s2_cr <= s1_cr;		s2_ci <= s1_ci;
			s2_cnt<= s1_cnt;	s2_esc <= s1_esc;
		end

		// ---- stage 3: + c, escape, count ----
		// mag > 4.0 in Q8.28 == mag >= 2^30 == any bit [35:30] set (mag >= 0),
		// a 1-LUT reduction instead of a full 36-bit compare.
		wire escaped_now = s2_esc | (|s2_mag[35 : 30]);

		always@(posedge pixel_clock)begin
			cr_p[i+1] <= s2_cr;
			ci_p[i+1] <= s2_ci;
			esc_p[i+1] <= escaped_now;
			if(escaped_now)begin
				cnt_p[i+1] <= s2_cnt;
				zr_p[i+1]  <= s2_zr;		// freeze z (stays bounded)
				zi_p[i+1]  <= s2_zi;
			end else begin
				cnt_p[i+1] <= s2_cnt + 1'b1;
				zr_p[i+1]  <= (s2_diff >>> FRAC) + s2_cr;		// zr^2 - zi^2 + cr
				zi_p[i+1]  <= (s2_ri >>> (FRAC - 1)) + s2_ci;	// 2*zr*zi + ci
			end
		end
	end endgenerate

	// ------------------------------------------------------------------
	// colour + output, with sync delayed to match the pipeline
	// ------------------------------------------------------------------

	localparam PIPE = 3*N + 2;

	reg		[23 : 0]	color;
	always@(posedge pixel_clock)
		color <= palette(cnt_p[N]);

	reg		[PIPE-1 : 0]	den_dly, hsync_dly, vsync_dly, line_start_dly;
	always@(posedge pixel_clock)begin
		den_dly			<= {den_dly[PIPE-2 : 0], den_int};
		hsync_dly		<= {hsync_dly[PIPE-2 : 0], hsync_int};
		vsync_dly		<= {vsync_dly[PIPE-2 : 0], vsync_int};
		line_start_dly	<= {line_start_dly[PIPE-2 : 0], line_start_int};
	end

	wire den_out = den_dly[PIPE-1];

	assign video_den		= den_out;
	assign video_hsync		= hsync_dly[PIPE-1];
	assign video_vsync		= vsync_dly[PIPE-1];
	assign video_line_start	= line_start_dly[PIPE-1];

	assign video_pixel_even	= den_out ? color : 24'h000000;
	assign video_pixel_odd	= den_out ? color : 24'h000000;

endmodule
