#!/usr/bin/env python3
"""
Turn the compiled firmware into the $readmemh file that boot_rom.v loads,
so the program ships inside the FPGA bitstream.

The ROM is 32 bits wide and the RISC-V image is little-endian, so every four
bytes become one hex word. The file is padded to the ROM depth: leaving
entries undefined would make them 'x' in simulation and unpredictable after
synthesis.

    python bin2vh.py firmware.bin boot_rom.vh --words 4096
"""
import argparse, os, sys


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("binary", help="firmware .bin (objcopy -O binary)")
    ap.add_argument("out", help="Verilog $readmemh output")
    ap.add_argument("--words", type=int, default=4096,
                    help="ROM depth in 32-bit words (default 4096 = 16 KB)")
    args = ap.parse_args()

    data = open(args.binary, "rb").read()

    # pad to a whole number of words
    if len(data) % 4:
        data += b"\x00" * (4 - len(data) % 4)
    nwords = len(data) // 4

    if nwords > args.words:
        sys.exit(f"error: firmware is {nwords} words ({len(data)} bytes) but the "
                 f"ROM holds {args.words}. Raise AW in top.v and LENGTH in ae350.ld.")

    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    with open(args.out, "w") as f:
        f.write(f"// generated by tools/bin2vh.py from {os.path.basename(args.binary)}\n")
        f.write(f"// {len(data)} bytes -> {nwords} words, padded to {args.words}\n")
        for i in range(args.words):
            if i < nwords:
                w = int.from_bytes(data[4 * i:4 * i + 4], "little")
            else:
                w = 0
            f.write(f"{w:08x}\n")

    pct = 100.0 * nwords / args.words
    print(f"wrote {args.out}: {len(data)} bytes, {nwords}/{args.words} words ({pct:.1f}% full)")


if __name__ == "__main__":
    main()
