#!/usr/bin/env python3
"""
Rasterise a monospace font into an 8x16 glyph ROM for the HDMI text console.

Covers printable ASCII 0x20..0x7E; each glyph is 16 rows of 8 bits, MSB = the
leftmost pixel, which is the order text_video.v shifts them out in. Emits
eda_proj/src/font_rom.vh for $readmemh and a preview sheet so the glyphs can be
eyeballed before committing them to a bitstream.
"""
import os, struct, zlib
from PIL import Image, ImageDraw, ImageFont

W, H = 8, 16                    # glyph cell in font pixels
FIRST, LAST = 0x20, 0x7E
COUNT = LAST - FIRST + 1

FONT_PATH = r"C:\Windows\Fonts\consola.ttf"
FONT_SIZE = 15                  # tuned so Consolas fills an 8x16 cell
X_OFF, Y_OFF = 0, -1            # nudge the glyph inside the cell
THRESHOLD = 110                 # ink/no-ink cut for the antialiased render


def render_glyphs():
    font = ImageFont.truetype(FONT_PATH, FONT_SIZE)
    glyphs = []
    for code in range(FIRST, LAST + 1):
        img = Image.new("L", (W, H), 0)
        ImageDraw.Draw(img).text((X_OFF, Y_OFF), chr(code), font=font, fill=255)
        rows = []
        for y in range(H):
            bits = 0
            for x in range(W):
                if img.getpixel((x, y)) >= THRESHOLD:
                    bits |= 0x80 >> x          # MSB = leftmost
            rows.append(bits)
        glyphs.append(rows)
    return glyphs


def emit_vh(glyphs, path):
    with open(path, "w") as f:
        f.write("// 8x16 glyph ROM, ASCII 0x%02X..0x%02X (generated by "
                "tools/make_font.py)\n" % (FIRST, LAST))
        f.write("// entry = (code - 0x%02X) * 16 + row; MSB is the left pixel\n"
                % FIRST)
        for code, rows in zip(range(FIRST, LAST + 1), glyphs):
            ch = chr(code) if code != 0x20 else "space"
            f.write("// '%s'\n" % ch)
            for r in rows:
                f.write("%02X\n" % r)
        # pad to a power of two so the ROM infers cleanly
        written = COUNT * H
        for _ in range(2048 - written):
            f.write("00\n")
    print("wrote %s: %d glyphs, %d bytes (padded to 2048)" %
          (path, COUNT, written))


def write_png(path, w, h, rows):
    def ch(t, d):
        c = t + d
        return struct.pack(">I", len(d)) + c + struct.pack(">I", zlib.crc32(c))
    raw = b"".join(b"\x00" + r for r in rows)
    open(path, "wb").write(
        b"\x89PNG\r\n\x1a\n"
        + ch(b"IHDR", struct.pack(">IIBBBBB", w, h, 8, 2, 0, 0, 0))
        + ch(b"IDAT", zlib.compress(raw, 9)) + ch(b"IEND", b""))


def preview(glyphs, path, cols=16, scale=2):
    """Sheet of every glyph, at the same 2x scale the hardware draws them."""
    rows_n = (COUNT + cols - 1) // cols
    pw, ph = cols * W * scale, rows_n * H * scale
    buf = [bytearray(b"\x10\x10\x18" * pw) for _ in range(ph)]
    for i, g in enumerate(glyphs):
        gx, gy = (i % cols) * W * scale, (i // cols) * H * scale
        for y in range(H):
            for x in range(W):
                if g[y] & (0x80 >> x):
                    for dy in range(scale):
                        row = buf[gy + y * scale + dy]
                        for dx in range(scale):
                            o = (gx + x * scale + dx) * 3
                            row[o:o + 3] = b"\xe8\xe8\xf0"
    write_png(path, pw, ph, [bytes(r) for r in buf])
    print("wrote", path)


if __name__ == "__main__":
    here = os.path.dirname(os.path.abspath(__file__))
    glyphs = render_glyphs()
    emit_vh(glyphs, os.path.join(here, "..", "eda_proj", "src", "font_rom.vh"))
    docs = os.path.join(here, "..", "docs")
    os.makedirs(docs, exist_ok=True)
    preview(glyphs, os.path.join(docs, "font_sheet.png"))
