`timescale 1ns / 1ns

//
// Animated Julia-set generator, 1920x1080@60.
//
// Same escape-time iteration as the Mandelbrot project (z <- z^2 + c) and the
// same timing-closed streaming pipeline, but:
//   * z0 = the pixel's complex coordinate (not 0);
//   * c  = a constant that walks a circle  c = 0.7885 * (cos t, sin t),
//     advanced one step every ANIM_DIV frames -> the fractal morphs.
// The iteration count (0..N) maps to colour through a "teal & orange" LUT.
// LUTs (c-circle and palette) are generated by tools/julia_model.py.
//
module julia_gen #(

	parameter video_hlength		= 2200,
	parameter video_vlength		= 1125,
	parameter video_hsync_pol	= 1,
	parameter video_hsync_len	= 44,
	parameter video_hbp_len		= 148,

	parameter video_h_visible	= 1920,
	parameter video_vsync_pol	= 1,
	parameter video_vsync_len	= 5,
	parameter video_vbp_len		= 36,
	parameter video_v_visible	= 1080,

	parameter N					= 14,	// iterations (== unrolled pipeline stages)
	parameter FRAC				= 14,	// Q4.14 fixed point
	parameter ANIM_DIV			= 2		// advance c one step every ANIM_DIV frames (~8.5 s / loop)
)
(
	input				pixel_clock,
	input				reset,

	output				video_vsync,
	output				video_hsync,
	output				video_den,
	output				video_line_start,
	output	[23 : 0]	video_pixel_even,
	output	[23 : 0]	video_pixel_odd
);

	// active-region boundaries in raster counter space
	localparam T_HVIS_BEGIN	= video_hsync_len + video_hbp_len;
	localparam T_HVIS_END	= T_HVIS_BEGIN + video_h_visible - 1;
	localparam T_VVIS_BEGIN	= video_vsync_len + video_vbp_len;

	// view window: centred on origin, square pixels (z0 = pixel coordinate)
	localparam signed [17 : 0]	ZR_STEP	= 18'sd27;
	localparam signed [17 : 0]	ZI_STEP	= 18'sd27;
	localparam signed [17 : 0]	ZR_MIN	= -(ZR_STEP * video_h_visible) / 2;
	localparam signed [17 : 0]	ZI_MIN	= -(ZI_STEP * video_v_visible) / 2;

	// c = 0.7885*(cos,sin) around a 256-step circle, Q4.14 (generated)
	function [35 : 0] c_lut(input [7 : 0] theta);  // {c_re[17:0], c_im[17:0]}
		case(theta)
			8'd0: c_lut = {18'h03277, 18'h00000};
			8'd1: c_lut = {18'h03273, 18'h0013D};
			8'd2: c_lut = {18'h03267, 18'h0027A};
			8'd3: c_lut = {18'h03254, 18'h003B6};
			8'd4: c_lut = {18'h03239, 18'h004F2};
			8'd5: c_lut = {18'h03216, 18'h0062D};
			8'd6: c_lut = {18'h031EB, 18'h00768};
			8'd7: c_lut = {18'h031B9, 18'h008A1};
			8'd8: c_lut = {18'h0317F, 18'h009D8};
			8'd9: c_lut = {18'h0313D, 18'h00B0F};
			8'd10: c_lut = {18'h030F4, 18'h00C43};
			8'd11: c_lut = {18'h030A3, 18'h00D76};
			8'd12: c_lut = {18'h0304B, 18'h00EA6};
			8'd13: c_lut = {18'h02FEB, 18'h00FD4};
			8'd14: c_lut = {18'h02F84, 18'h01100};
			8'd15: c_lut = {18'h02F15, 18'h01229};
			8'd16: c_lut = {18'h02E9F, 18'h01350};
			8'd17: c_lut = {18'h02E22, 18'h01473};
			8'd18: c_lut = {18'h02D9E, 18'h01593};
			8'd19: c_lut = {18'h02D13, 18'h016B0};
			8'd20: c_lut = {18'h02C81, 18'h017CA};
			8'd21: c_lut = {18'h02BE8, 18'h018E0};
			8'd22: c_lut = {18'h02B49, 18'h019F2};
			8'd23: c_lut = {18'h02AA2, 18'h01B00};
			8'd24: c_lut = {18'h029F6, 18'h01C09};
			8'd25: c_lut = {18'h02942, 18'h01D0F};
			8'd26: c_lut = {18'h02888, 18'h01E10};
			8'd27: c_lut = {18'h027C8, 18'h01F0C};
			8'd28: c_lut = {18'h02702, 18'h02004};
			8'd29: c_lut = {18'h02636, 18'h020F6};
			8'd30: c_lut = {18'h02564, 18'h021E4};
			8'd31: c_lut = {18'h0248C, 18'h022CC};
			8'd32: c_lut = {18'h023AF, 18'h023AF};
			8'd33: c_lut = {18'h022CC, 18'h0248C};
			8'd34: c_lut = {18'h021E4, 18'h02564};
			8'd35: c_lut = {18'h020F6, 18'h02636};
			8'd36: c_lut = {18'h02004, 18'h02702};
			8'd37: c_lut = {18'h01F0C, 18'h027C8};
			8'd38: c_lut = {18'h01E10, 18'h02888};
			8'd39: c_lut = {18'h01D0F, 18'h02942};
			8'd40: c_lut = {18'h01C09, 18'h029F6};
			8'd41: c_lut = {18'h01B00, 18'h02AA2};
			8'd42: c_lut = {18'h019F2, 18'h02B49};
			8'd43: c_lut = {18'h018E0, 18'h02BE8};
			8'd44: c_lut = {18'h017CA, 18'h02C81};
			8'd45: c_lut = {18'h016B0, 18'h02D13};
			8'd46: c_lut = {18'h01593, 18'h02D9E};
			8'd47: c_lut = {18'h01473, 18'h02E22};
			8'd48: c_lut = {18'h01350, 18'h02E9F};
			8'd49: c_lut = {18'h01229, 18'h02F15};
			8'd50: c_lut = {18'h01100, 18'h02F84};
			8'd51: c_lut = {18'h00FD4, 18'h02FEB};
			8'd52: c_lut = {18'h00EA6, 18'h0304B};
			8'd53: c_lut = {18'h00D76, 18'h030A3};
			8'd54: c_lut = {18'h00C43, 18'h030F4};
			8'd55: c_lut = {18'h00B0F, 18'h0313D};
			8'd56: c_lut = {18'h009D8, 18'h0317F};
			8'd57: c_lut = {18'h008A1, 18'h031B9};
			8'd58: c_lut = {18'h00768, 18'h031EB};
			8'd59: c_lut = {18'h0062D, 18'h03216};
			8'd60: c_lut = {18'h004F2, 18'h03239};
			8'd61: c_lut = {18'h003B6, 18'h03254};
			8'd62: c_lut = {18'h0027A, 18'h03267};
			8'd63: c_lut = {18'h0013D, 18'h03273};
			8'd64: c_lut = {18'h00000, 18'h03277};
			8'd65: c_lut = {18'h3FEC3, 18'h03273};
			8'd66: c_lut = {18'h3FD86, 18'h03267};
			8'd67: c_lut = {18'h3FC4A, 18'h03254};
			8'd68: c_lut = {18'h3FB0E, 18'h03239};
			8'd69: c_lut = {18'h3F9D3, 18'h03216};
			8'd70: c_lut = {18'h3F898, 18'h031EB};
			8'd71: c_lut = {18'h3F75F, 18'h031B9};
			8'd72: c_lut = {18'h3F628, 18'h0317F};
			8'd73: c_lut = {18'h3F4F1, 18'h0313D};
			8'd74: c_lut = {18'h3F3BD, 18'h030F4};
			8'd75: c_lut = {18'h3F28A, 18'h030A3};
			8'd76: c_lut = {18'h3F15A, 18'h0304B};
			8'd77: c_lut = {18'h3F02C, 18'h02FEB};
			8'd78: c_lut = {18'h3EF00, 18'h02F84};
			8'd79: c_lut = {18'h3EDD7, 18'h02F15};
			8'd80: c_lut = {18'h3ECB0, 18'h02E9F};
			8'd81: c_lut = {18'h3EB8D, 18'h02E22};
			8'd82: c_lut = {18'h3EA6D, 18'h02D9E};
			8'd83: c_lut = {18'h3E950, 18'h02D13};
			8'd84: c_lut = {18'h3E836, 18'h02C81};
			8'd85: c_lut = {18'h3E720, 18'h02BE8};
			8'd86: c_lut = {18'h3E60E, 18'h02B49};
			8'd87: c_lut = {18'h3E500, 18'h02AA2};
			8'd88: c_lut = {18'h3E3F7, 18'h029F6};
			8'd89: c_lut = {18'h3E2F1, 18'h02942};
			8'd90: c_lut = {18'h3E1F0, 18'h02888};
			8'd91: c_lut = {18'h3E0F4, 18'h027C8};
			8'd92: c_lut = {18'h3DFFC, 18'h02702};
			8'd93: c_lut = {18'h3DF0A, 18'h02636};
			8'd94: c_lut = {18'h3DE1C, 18'h02564};
			8'd95: c_lut = {18'h3DD34, 18'h0248C};
			8'd96: c_lut = {18'h3DC51, 18'h023AF};
			8'd97: c_lut = {18'h3DB74, 18'h022CC};
			8'd98: c_lut = {18'h3DA9C, 18'h021E4};
			8'd99: c_lut = {18'h3D9CA, 18'h020F6};
			8'd100: c_lut = {18'h3D8FE, 18'h02004};
			8'd101: c_lut = {18'h3D838, 18'h01F0C};
			8'd102: c_lut = {18'h3D778, 18'h01E10};
			8'd103: c_lut = {18'h3D6BE, 18'h01D0F};
			8'd104: c_lut = {18'h3D60A, 18'h01C09};
			8'd105: c_lut = {18'h3D55E, 18'h01B00};
			8'd106: c_lut = {18'h3D4B7, 18'h019F2};
			8'd107: c_lut = {18'h3D418, 18'h018E0};
			8'd108: c_lut = {18'h3D37F, 18'h017CA};
			8'd109: c_lut = {18'h3D2ED, 18'h016B0};
			8'd110: c_lut = {18'h3D262, 18'h01593};
			8'd111: c_lut = {18'h3D1DE, 18'h01473};
			8'd112: c_lut = {18'h3D161, 18'h01350};
			8'd113: c_lut = {18'h3D0EB, 18'h01229};
			8'd114: c_lut = {18'h3D07C, 18'h01100};
			8'd115: c_lut = {18'h3D015, 18'h00FD4};
			8'd116: c_lut = {18'h3CFB5, 18'h00EA6};
			8'd117: c_lut = {18'h3CF5D, 18'h00D76};
			8'd118: c_lut = {18'h3CF0C, 18'h00C43};
			8'd119: c_lut = {18'h3CEC3, 18'h00B0F};
			8'd120: c_lut = {18'h3CE81, 18'h009D8};
			8'd121: c_lut = {18'h3CE47, 18'h008A1};
			8'd122: c_lut = {18'h3CE15, 18'h00768};
			8'd123: c_lut = {18'h3CDEA, 18'h0062D};
			8'd124: c_lut = {18'h3CDC7, 18'h004F2};
			8'd125: c_lut = {18'h3CDAC, 18'h003B6};
			8'd126: c_lut = {18'h3CD99, 18'h0027A};
			8'd127: c_lut = {18'h3CD8D, 18'h0013D};
			8'd128: c_lut = {18'h3CD89, 18'h00000};
			8'd129: c_lut = {18'h3CD8D, 18'h3FEC3};
			8'd130: c_lut = {18'h3CD99, 18'h3FD86};
			8'd131: c_lut = {18'h3CDAC, 18'h3FC4A};
			8'd132: c_lut = {18'h3CDC7, 18'h3FB0E};
			8'd133: c_lut = {18'h3CDEA, 18'h3F9D3};
			8'd134: c_lut = {18'h3CE15, 18'h3F898};
			8'd135: c_lut = {18'h3CE47, 18'h3F75F};
			8'd136: c_lut = {18'h3CE81, 18'h3F628};
			8'd137: c_lut = {18'h3CEC3, 18'h3F4F1};
			8'd138: c_lut = {18'h3CF0C, 18'h3F3BD};
			8'd139: c_lut = {18'h3CF5D, 18'h3F28A};
			8'd140: c_lut = {18'h3CFB5, 18'h3F15A};
			8'd141: c_lut = {18'h3D015, 18'h3F02C};
			8'd142: c_lut = {18'h3D07C, 18'h3EF00};
			8'd143: c_lut = {18'h3D0EB, 18'h3EDD7};
			8'd144: c_lut = {18'h3D161, 18'h3ECB0};
			8'd145: c_lut = {18'h3D1DE, 18'h3EB8D};
			8'd146: c_lut = {18'h3D262, 18'h3EA6D};
			8'd147: c_lut = {18'h3D2ED, 18'h3E950};
			8'd148: c_lut = {18'h3D37F, 18'h3E836};
			8'd149: c_lut = {18'h3D418, 18'h3E720};
			8'd150: c_lut = {18'h3D4B7, 18'h3E60E};
			8'd151: c_lut = {18'h3D55E, 18'h3E500};
			8'd152: c_lut = {18'h3D60A, 18'h3E3F7};
			8'd153: c_lut = {18'h3D6BE, 18'h3E2F1};
			8'd154: c_lut = {18'h3D778, 18'h3E1F0};
			8'd155: c_lut = {18'h3D838, 18'h3E0F4};
			8'd156: c_lut = {18'h3D8FE, 18'h3DFFC};
			8'd157: c_lut = {18'h3D9CA, 18'h3DF0A};
			8'd158: c_lut = {18'h3DA9C, 18'h3DE1C};
			8'd159: c_lut = {18'h3DB74, 18'h3DD34};
			8'd160: c_lut = {18'h3DC51, 18'h3DC51};
			8'd161: c_lut = {18'h3DD34, 18'h3DB74};
			8'd162: c_lut = {18'h3DE1C, 18'h3DA9C};
			8'd163: c_lut = {18'h3DF0A, 18'h3D9CA};
			8'd164: c_lut = {18'h3DFFC, 18'h3D8FE};
			8'd165: c_lut = {18'h3E0F4, 18'h3D838};
			8'd166: c_lut = {18'h3E1F0, 18'h3D778};
			8'd167: c_lut = {18'h3E2F1, 18'h3D6BE};
			8'd168: c_lut = {18'h3E3F7, 18'h3D60A};
			8'd169: c_lut = {18'h3E500, 18'h3D55E};
			8'd170: c_lut = {18'h3E60E, 18'h3D4B7};
			8'd171: c_lut = {18'h3E720, 18'h3D418};
			8'd172: c_lut = {18'h3E836, 18'h3D37F};
			8'd173: c_lut = {18'h3E950, 18'h3D2ED};
			8'd174: c_lut = {18'h3EA6D, 18'h3D262};
			8'd175: c_lut = {18'h3EB8D, 18'h3D1DE};
			8'd176: c_lut = {18'h3ECB0, 18'h3D161};
			8'd177: c_lut = {18'h3EDD7, 18'h3D0EB};
			8'd178: c_lut = {18'h3EF00, 18'h3D07C};
			8'd179: c_lut = {18'h3F02C, 18'h3D015};
			8'd180: c_lut = {18'h3F15A, 18'h3CFB5};
			8'd181: c_lut = {18'h3F28A, 18'h3CF5D};
			8'd182: c_lut = {18'h3F3BD, 18'h3CF0C};
			8'd183: c_lut = {18'h3F4F1, 18'h3CEC3};
			8'd184: c_lut = {18'h3F628, 18'h3CE81};
			8'd185: c_lut = {18'h3F75F, 18'h3CE47};
			8'd186: c_lut = {18'h3F898, 18'h3CE15};
			8'd187: c_lut = {18'h3F9D3, 18'h3CDEA};
			8'd188: c_lut = {18'h3FB0E, 18'h3CDC7};
			8'd189: c_lut = {18'h3FC4A, 18'h3CDAC};
			8'd190: c_lut = {18'h3FD86, 18'h3CD99};
			8'd191: c_lut = {18'h3FEC3, 18'h3CD8D};
			8'd192: c_lut = {18'h00000, 18'h3CD89};
			8'd193: c_lut = {18'h0013D, 18'h3CD8D};
			8'd194: c_lut = {18'h0027A, 18'h3CD99};
			8'd195: c_lut = {18'h003B6, 18'h3CDAC};
			8'd196: c_lut = {18'h004F2, 18'h3CDC7};
			8'd197: c_lut = {18'h0062D, 18'h3CDEA};
			8'd198: c_lut = {18'h00768, 18'h3CE15};
			8'd199: c_lut = {18'h008A1, 18'h3CE47};
			8'd200: c_lut = {18'h009D8, 18'h3CE81};
			8'd201: c_lut = {18'h00B0F, 18'h3CEC3};
			8'd202: c_lut = {18'h00C43, 18'h3CF0C};
			8'd203: c_lut = {18'h00D76, 18'h3CF5D};
			8'd204: c_lut = {18'h00EA6, 18'h3CFB5};
			8'd205: c_lut = {18'h00FD4, 18'h3D015};
			8'd206: c_lut = {18'h01100, 18'h3D07C};
			8'd207: c_lut = {18'h01229, 18'h3D0EB};
			8'd208: c_lut = {18'h01350, 18'h3D161};
			8'd209: c_lut = {18'h01473, 18'h3D1DE};
			8'd210: c_lut = {18'h01593, 18'h3D262};
			8'd211: c_lut = {18'h016B0, 18'h3D2ED};
			8'd212: c_lut = {18'h017CA, 18'h3D37F};
			8'd213: c_lut = {18'h018E0, 18'h3D418};
			8'd214: c_lut = {18'h019F2, 18'h3D4B7};
			8'd215: c_lut = {18'h01B00, 18'h3D55E};
			8'd216: c_lut = {18'h01C09, 18'h3D60A};
			8'd217: c_lut = {18'h01D0F, 18'h3D6BE};
			8'd218: c_lut = {18'h01E10, 18'h3D778};
			8'd219: c_lut = {18'h01F0C, 18'h3D838};
			8'd220: c_lut = {18'h02004, 18'h3D8FE};
			8'd221: c_lut = {18'h020F6, 18'h3D9CA};
			8'd222: c_lut = {18'h021E4, 18'h3DA9C};
			8'd223: c_lut = {18'h022CC, 18'h3DB74};
			8'd224: c_lut = {18'h023AF, 18'h3DC51};
			8'd225: c_lut = {18'h0248C, 18'h3DD34};
			8'd226: c_lut = {18'h02564, 18'h3DE1C};
			8'd227: c_lut = {18'h02636, 18'h3DF0A};
			8'd228: c_lut = {18'h02702, 18'h3DFFC};
			8'd229: c_lut = {18'h027C8, 18'h3E0F4};
			8'd230: c_lut = {18'h02888, 18'h3E1F0};
			8'd231: c_lut = {18'h02942, 18'h3E2F1};
			8'd232: c_lut = {18'h029F6, 18'h3E3F7};
			8'd233: c_lut = {18'h02AA2, 18'h3E500};
			8'd234: c_lut = {18'h02B49, 18'h3E60E};
			8'd235: c_lut = {18'h02BE8, 18'h3E720};
			8'd236: c_lut = {18'h02C81, 18'h3E836};
			8'd237: c_lut = {18'h02D13, 18'h3E950};
			8'd238: c_lut = {18'h02D9E, 18'h3EA6D};
			8'd239: c_lut = {18'h02E22, 18'h3EB8D};
			8'd240: c_lut = {18'h02E9F, 18'h3ECB0};
			8'd241: c_lut = {18'h02F15, 18'h3EDD7};
			8'd242: c_lut = {18'h02F84, 18'h3EF00};
			8'd243: c_lut = {18'h02FEB, 18'h3F02C};
			8'd244: c_lut = {18'h0304B, 18'h3F15A};
			8'd245: c_lut = {18'h030A3, 18'h3F28A};
			8'd246: c_lut = {18'h030F4, 18'h3F3BD};
			8'd247: c_lut = {18'h0313D, 18'h3F4F1};
			8'd248: c_lut = {18'h0317F, 18'h3F628};
			8'd249: c_lut = {18'h031B9, 18'h3F75F};
			8'd250: c_lut = {18'h031EB, 18'h3F898};
			8'd251: c_lut = {18'h03216, 18'h3F9D3};
			8'd252: c_lut = {18'h03239, 18'h3FB0E};
			8'd253: c_lut = {18'h03254, 18'h3FC4A};
			8'd254: c_lut = {18'h03267, 18'h3FD86};
			8'd255: c_lut = {18'h03273, 18'h3FEC3};
			default: c_lut = 36'h0;
		endcase
	endfunction

	function [23 : 0] palette(input [6 : 0] cnt);
		case(cnt)
			7'd0: palette = 24'h061626;
			7'd1: palette = 24'h0B3548;
			7'd2: palette = 24'h105469;
			7'd3: palette = 24'h17788B;
			7'd4: palette = 24'h209DAC;
			7'd5: palette = 24'h36BBC5;
			7'd6: palette = 24'h52D5DB;
			7'd7: palette = 24'h76E8EA;
			7'd8: palette = 24'hA2F4F2;
			7'd9: palette = 24'hD0F9F2;
			7'd10: palette = 24'hF9F1E4;
			7'd11: palette = 24'hF4A97E;
			7'd12: palette = 24'hD76D28;
			7'd13: palette = 24'h78281C;
			7'd14: palette = 24'h000000;
			default: palette = 24'h000000;
		endcase
	endfunction

	// ------------------------------------------------------------------
	// video timing
	// ------------------------------------------------------------------

	wire	[13 : 0]	timing_h_pos;
	wire	[13 : 0]	timing_v_pos;
	wire	[13 : 0]	pixel_x_nc;
	wire	[13 : 0]	pixel_y_nc;

	wire				vsync_int;
	wire				hsync_int;
	wire				den_int;
	wire				line_start_int;

	video_timing_ctrl #(
		.video_hlength(video_hlength),
		.video_vlength(video_vlength),
		.video_hsync_pol(video_hsync_pol),
		.video_hsync_len(video_hsync_len),
		.video_hbp_len(video_hbp_len),
		.video_h_visible(video_h_visible),
		.video_vsync_pol(video_vsync_pol),
		.video_vsync_len(video_vsync_len),
		.video_vbp_len(video_vbp_len),
		.video_v_visible(video_v_visible)
	)video_timing_ctrl_inst0(
		.pixel_clock		(pixel_clock),
		.reset				(reset),
		.ext_sync			(1'b0),
		.timing_h_pos		(timing_h_pos),
		.timing_v_pos		(timing_v_pos),
		.pixel_x			(pixel_x_nc),
		.pixel_y			(pixel_y_nc),
		.video_vsync		(vsync_int),
		.video_hsync		(hsync_int),
		.video_den			(den_int),
		.video_line_start	(line_start_int)
	);

	// ------------------------------------------------------------------
	// animation: advance the c-circle angle once every ANIM_DIV frames
	// ------------------------------------------------------------------

	wire frame_tick = (timing_h_pos == 0) && (timing_v_pos == 0);

	reg		[7 : 0]		frame_div	= 0;
	reg		[7 : 0]		theta		= 0;

	always@(posedge pixel_clock)begin
		if(reset)begin
			frame_div <= 0;
			theta <= 0;
		end else if(frame_tick)begin
			if(frame_div == (ANIM_DIV - 1))begin
				frame_div <= 0;
				theta <= theta + 1'b1;		// 8-bit wrap == full circle
			end else begin
				frame_div <= frame_div + 1'b1;
			end
		end
	end

	// c for the current frame (theta is stable through the visible region).
	// Registering the whole LUT output maps the 256x36 table to a BSRAM ROM
	// instead of ~900 fabric LUTs (which otherwise congest the DSP pipeline).
	reg	[35 : 0]	c_word;
	always@(posedge pixel_clock)
		c_word <= c_lut(theta);
	wire signed	[17 : 0]	c_re = c_word[35 : 18];
	wire signed	[17 : 0]	c_im = c_word[17 : 0];

	// ------------------------------------------------------------------
	// pixel -> z0 coordinate (DDA, adders only), aligned with den_int
	// ------------------------------------------------------------------

	wire pix_load  = (timing_h_pos == (T_HVIS_BEGIN - 1));
	wire line_step = (timing_h_pos == (T_HVIS_END + 1));
	wire frame_load= (timing_v_pos == (T_VVIS_BEGIN - 1));

	reg signed	[17 : 0]	zi_line	= 0;
	always@(posedge pixel_clock)begin
		if(line_step)
			zi_line <= frame_load ? ZI_MIN : (zi_line + ZI_STEP);
	end

	reg signed	[17 : 0]	zr_pixel = 0;
	always@(posedge pixel_clock)begin
		if(pix_load)	zr_pixel <= ZR_MIN;
		else			zr_pixel <= zr_pixel + ZR_STEP;
	end

	// ------------------------------------------------------------------
	// unrolled iteration pipeline (identical to the Mandelbrot engine)
	// ------------------------------------------------------------------

	reg signed	[17 : 0]	zr_p [0 : N];
	reg signed	[17 : 0]	zi_p [0 : N];
	reg signed	[17 : 0]	cr_p [0 : N];
	reg signed	[17 : 0]	ci_p [0 : N];
	reg			[6 : 0]		cnt_p [0 : N];
	reg						esc_p [0 : N];

	// stage 0: inject z0 = pixel, c = animated constant
	always@(posedge pixel_clock)begin
		zr_p[0] <= zr_pixel;
		zi_p[0] <= zi_line;
		cr_p[0] <= c_re;
		ci_p[0] <= c_im;
		cnt_p[0] <= 7'd0;
		esc_p[0] <= 1'b0;
	end

	// Each iteration is 3 registered stages so no two DSPs are chained
	// combinationally (products feed both the sum and difference so the
	// tool can't fold product+add into one MULTADD and eat the register).
	genvar i;
	generate for(i = 0; i < N; i = i + 1) begin : iter

		// ---- stage 1: products ----
		reg signed	[35 : 0]	m_rr, m_ii, m_ri;
		reg signed	[17 : 0]	s1_zr, s1_zi, s1_cr, s1_ci;
		reg			[6 : 0]		s1_cnt;
		reg						s1_esc;

		always@(posedge pixel_clock)begin
			m_rr  <= zr_p[i] * zr_p[i];
			m_ii  <= zi_p[i] * zi_p[i];
			m_ri  <= zr_p[i] * zi_p[i];
			s1_zr <= zr_p[i];	s1_zi <= zi_p[i];
			s1_cr <= cr_p[i];	s1_ci <= ci_p[i];
			s1_cnt<= cnt_p[i];	s1_esc <= esc_p[i];
		end

		// ---- stage 2: combine products ----
		reg signed	[35 : 0]	s2_diff, s2_mag, s2_ri;
		reg signed	[17 : 0]	s2_zr, s2_zi, s2_cr, s2_ci;
		reg			[6 : 0]		s2_cnt;
		reg						s2_esc;

		always@(posedge pixel_clock)begin
			s2_diff <= m_rr - m_ii;
			s2_mag  <= m_rr + m_ii;
			s2_ri   <= m_ri;
			s2_zr <= s1_zr;		s2_zi <= s1_zi;
			s2_cr <= s1_cr;		s2_ci <= s1_ci;
			s2_cnt<= s1_cnt;	s2_esc <= s1_esc;
		end

		// ---- stage 3: + c, escape, count ----
		wire escaped_now = s2_esc | (|s2_mag[35 : 30]);

		always@(posedge pixel_clock)begin
			cr_p[i+1] <= s2_cr;
			ci_p[i+1] <= s2_ci;
			esc_p[i+1] <= escaped_now;
			if(escaped_now)begin
				cnt_p[i+1] <= s2_cnt;
				zr_p[i+1]  <= s2_zr;
				zi_p[i+1]  <= s2_zi;
			end else begin
				cnt_p[i+1] <= s2_cnt + 1'b1;
				zr_p[i+1]  <= (s2_diff >>> FRAC) + s2_cr;
				zi_p[i+1]  <= (s2_ri >>> (FRAC - 1)) + s2_ci;
			end
		end
	end endgenerate

	// ------------------------------------------------------------------
	// colour + output, sync delayed to match the pipeline
	// ------------------------------------------------------------------

	localparam PIPE = 3*N + 2;

	reg		[23 : 0]	color;
	always@(posedge pixel_clock)
		color <= palette(cnt_p[N]);

	reg		[PIPE-1 : 0]	den_dly, hsync_dly, vsync_dly, line_start_dly;
	always@(posedge pixel_clock)begin
		den_dly			<= {den_dly[PIPE-2 : 0], den_int};
		hsync_dly		<= {hsync_dly[PIPE-2 : 0], hsync_int};
		vsync_dly		<= {vsync_dly[PIPE-2 : 0], vsync_int};
		line_start_dly	<= {line_start_dly[PIPE-2 : 0], line_start_int};
	end

	wire den_out = den_dly[PIPE-1];

	assign video_den		= den_out;
	assign video_hsync		= hsync_dly[PIPE-1];
	assign video_vsync		= vsync_dly[PIPE-1];
	assign video_line_start	= line_start_dly[PIPE-1];

	assign video_pixel_even	= den_out ? color : 24'h000000;
	assign video_pixel_odd	= den_out ? color : 24'h000000;

endmodule
